# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u0422\u044d\u0433',
                'verbose_name_plural': '\u0422\u044d\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='textform.Tag'),
        ),
    ]
