# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textform', '0002_auto_20160419_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
