# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textform', '0005_auto_20160401_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='like_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
